version: 0.2
phases:
  build:
    commands:
      - pip install mkdocs
      - mkdocs build
      - pip install awscli
      - aws s3 cp site s3://mtec-bls-fall-2017 --recursive
artifacts:
  files:
    - site/**/*
